CREATE TABLE users(
id INT UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
firstName VARCHAR(32) NOT NULL,
lastName VARCHAR(32) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
phoneNumber INT NOT NULL UNIQUE,
streetAddress VARCHAR(255),
aptAdress VARCHAR(32),
city VARCHAR(32),
stateCode VARCHAR(12),
zipcode INT,
verified BOOLEAN DEFAULT '0',
employee BOOLEAN DEFAULT '0',
token VARCHAR(255)
);
CREATE TABLE orders(
id INT UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
userID INT REFERENCES users(id),
employeeID INT REFERENCES users(id),
delivery VARCHAR(32) NOT NULL,
payment INT NOT NULL,
approved BOOLEAN DEFAULT '0'
);
CREATE TABLE products(
id INT UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
orderid INT REFERENCES orders(id),
width FLOAT NOT NULL,
height FLOAT NOT NULL,
type VARCHAR(32) NOT NULL,
quantity INT NOT NULL
)